# Purpose: (VCF) Rename the individual names within a VCF file using bcftools.
#
#          Varient of 'vcf_inds_rename.sh' with _JC and _JA labels includes.
#          Generates mapping.txt file to enable swapping back and forth if needed. 

# INPUTS
VCF_FILE_LOC=$1
OUTPUT_LOC=$2
OUTPUT_VCF_FILE=$3

# JC and JA labels for the data required for renaming
JC_JA_LABELS_FILE=$4  # This is a text file with the JC/JA label for each individual
                      # is specified in the order of individuals
                      # and are generated by 'subset_JCvsJA_ebrahimi' for example

echo $JC_JA_LABELS_FILE

# Save old VCF individual names into text
bcftools query -l $VCF_FILE_LOC > original_ids.txt

# Create a new list of names based on lengths of the original_ids length
    # w1 adds a column for the line number in column 1 ($1)
nl -w1 original_ids.txt | awk '{print "IND"$1}' > numbered_ids.txt
paste numbered_ids.txt <(awk '{print $1}' "$JC_JA_LABELS_FILE") | \
awk '{print $1"_"$2}' > list_complete_ids.txt 

# Rename individuals 
bcftools reheader -s list_complete_ids.txt $VCF_FILE_LOC > "$OUTPUT_VCF_FILE"

mv list_complete_ids.txt "$OUTPUT_LOC/list_complete_ids.txt"
mv original_ids.txt "$OUTPUT_LOC/original_ids.txt"
rm numbered_ids.txt # remove intermediate


# Use the mappings as follows 
# Ex: nl mapping.txt | awk '{print $2}' > select_INDS.txt
# head -n $NUM_INDS $IND_MAPPING_FILE | awk '{print $1}' > samples.txt          # Generates the text with IDs to retain

